<?php echo $this->doctype() ?>

<html lang="ru">
    <head>
        <?php
            echo $this->headTitle('cavas test project')->setSeparator(' - ')->setAutoEscape(false);

            echo $this->headMeta()
                ->setCharset('utf-8')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

            echo $this->headScript();

            echo $this->headLink();
        ?>
    </head>
    <body>
        <nav>
            <a href="<?php echo $this->url('home') ?>">Создание изображения</a>
            <a href="<?php echo $this->url('home', ['action' => 'list']) ?>">Галерея</a>
        </nav>
        <?php echo $this->content ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
